# Generated by Django 3.2 on 2021-10-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastedsales',
            unique_together={('model_name', 'date', 'horizon')},
        ),
    ]
