# Generated by Django 3.2 on 2021-10-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dci',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='product',
            name='designation',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='forme',
            field=models.CharField(max_length=300),
        ),
    ]
