# Generated by Django 3.2 on 2021-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211003_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_prod',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
