# Generated by Django 3.2 on 2021-09-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_actualsales_adjustedsales_date_forecastedsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastedsales',
            name='model_name',
            field=models.CharField(default='auto', max_length=50),
        ),
        migrations.AlterField(
            model_name='actualsales',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualsale', to='products.date'),
        ),
        migrations.AlterField(
            model_name='actualsales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='products.product'),
        ),
    ]
