# Generated by Django 3.2.7 on 2021-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_actualsales_adjustedsales_date_forecastedsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='id_date',
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=None, primary_key=True, serialize=False),
        ),
    ]
