# Generated by Django 3.2 on 2021-09-21 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210920_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastedsales',
            name='horizon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adjustedsales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusted', to='products.product'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='forecastedsales',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecastsale', to='products.date'),
        ),
        migrations.AlterField(
            model_name='forecastedsales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastedsales',
            unique_together={('date', 'horizon')},
        ),
    ]
