# Generated by Django 3.2 on 2021-09-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210921_2205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastedsales',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='forecastedsales',
            name='horizon',
        ),
    ]
