# Generated by Django 3.2 on 2021-09-21 21:19

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210921_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
