# Generated by Django 3.2 on 2021-09-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastedsales',
            name='horizon',
            field=models.IntegerField(default=0),
        ),
    ]
