# Generated by Django 3.2 on 2021-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_forecastedsales_horizon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastedsales',
            name='horizon',
            field=models.IntegerField(default=None),
        ),
    ]
