# Generated by Django 3.2 on 2021-09-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_forecastedsales_horizon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastedsales',
            unique_together={('date', 'horizon')},
        ),
    ]
